// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";

function convertToJs(validation) {
  if (validation.tag) {
    return Belt_List.toArray(List.map((function (f) {
                      return {
                              path: f[/* path */0],
                              message: f[/* message */1]
                            };
                    }), validation[0]));
  } else {
    return /* array */[];
  }
}

function doValidation(validator, value, path) {
  return Curry._2(validator, value, path);
}

function validate(validator, value) {
  return convertToJs(Curry._2(validator, value, ""));
}

export {
  convertToJs ,
  doValidation ,
  validate ,
  
}
/* No side effect */
