// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function convertToJs(validation) {
  if (validation) {
    return Belt_List.toArray(List.map((function (f) {
                      return {
                              path: f[/* path */0],
                              message: f[/* message */1]
                            };
                    }), validation[0]));
  } else {
    return /* array */[];
  }
}

function doValidation(validator, value) {
  return Curry._1(validator, value);
}

function validate(validator, value) {
  return convertToJs(Curry._1(validator, value));
}

exports.convertToJs = convertToJs;
exports.doValidation = doValidation;
exports.validate = validate;
/* No side effect */
